version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-regular_payments}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dao-service:
    build:
      context: dao-service
    container_name: dao-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${DATABASE_URL:-jdbc:postgresql://postgres:5432/regular_payments}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres-data: