spring:
  profiles:
    active: local

  flyway:
    schemas: regular_payments


  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: regular_payments

server:
  port: 8081
